### ISSUE TITLE
minDate / maxDate dates bug?

### ISSUE THREAD

**Issue by nanotime** [pushtell/react-bootstrap-date-picker#134]
I worked with react-bootstrap-date-picker in the pasts and never have a problem.

I'm passing to the `<DatePicker />` component the `minDate` `maxDate` props (like always) and, well, im getting this error:

> Uncaught TypeError: Cannot read property 'slice' of undefined

The dates are strings, ISO strings to be precise:

minDate: 2017-06-01T00:00:00.000Z
maxDate: 2017-06-30T00:00:00.000Z

And the code:

```jsx
<DatePicker
  minDate='2017-06-01T00:00:00.000Z'
  maxDate='2017-06-30T00:00:00.000Z'
/>
```

Any idea? This never happened before.

**Comment by charrison-symfact** [comment]
I'm getting this too.

**Comment by psudeepta** [comment]
even I'm getting.

**Comment by SergeyZubkov** [comment]
need set defalut value in input - ISOString

**Comment by flygis** [comment]
Im getting the same error here, here is my component: 
<DatePicker
dateFormat='DD.MM.YYYY'
defaultValue={new Date().toISOString()}
minDate={new Date().toISOString()}
onChange={nextProps.handleReturnDateChange}
showClearButton={false}
weekStartsOn={1}>

**Comment by travellingprog** [comment]
I've made a branch in my fork that fixes this. You can install it in your package.json, or you can install [this branch](https://github.com/travellingprog/react-bootstrap-date-picker/tree/fix-makeDateValue-bug), which also includes another min/maxDate-related bug fix, described in PR #131.

For example, I use Yarn, so I was able to get both those fixes in my app by running:

```sh
# remove current version
yarn remove react-bootstrap-date-picker

# install branch with fixes
yarn add "https://github.com/travellingprog/react-bootstrap-date-picker#fix-makeDateValue-bug"
```

**Comment by MarcusMann** [comment]
Did you make a pr? @travellingprog

**Comment by travellingprog** [comment]
@MarcusMann yeah, it's PR #137

**Comment by JonShort** [comment]
I've merged PR #137 - so this bug should be fixed now 👍

**Comment by glennWerner** [comment]
I'm using the latest version and I am still getting this error when trying to set minDate.

**Comment by seangarita** [comment]
@glennWerner  It's because of this month old issue: https://github.com/pushtell/react-bootstrap-date-picker/issues/139 . Unclear why the package has not been able to be updated.

**Comment by wehriam** [comment]
@glennWerner and @seangarita this is a community supported project. We've done our best to share this code but are not always available to review and release updates.

If you're interested in professional support feel free to contact me directly.
